"""initial

Revision ID: 15ca813bb495
Revises: 
Create Date: 2026-03-04 14:04:28.600951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ca813bb495'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('anthropic_request_id', sa.String(length=64), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('endpoint', sa.String(length=256), nullable=False),
    sa.Column('is_streaming', sa.Boolean(), nullable=False),
    sa.Column('stop_reason', sa.String(length=64), nullable=True),
    sa.Column('system_prompt_preview', sa.String(length=500), nullable=True),
    sa.Column('first_user_message_preview', sa.String(length=500), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_requests', schema=None) as batch_op:
        batch_op.create_index('ix_api_requests_model', ['model'], unique=False)
        batch_op.create_index('ix_api_requests_requested_at', ['requested_at'], unique=False)

    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=False),
    sa.Column('input_cost_usd', sa.Float(), nullable=False),
    sa.Column('output_cost_usd', sa.Float(), nullable=False),
    sa.Column('cache_read_cost_usd', sa.Float(), nullable=False),
    sa.Column('cache_creation_cost_usd', sa.Float(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['api_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.create_index('ix_api_usage_total_cost_usd', ['total_cost_usd'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.drop_index('ix_api_usage_total_cost_usd')

    op.drop_table('api_usage')
    with op.batch_alter_table('api_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_api_requests_requested_at')
        batch_op.drop_index('ix_api_requests_model')

    op.drop_table('api_requests')
    # ### end Alembic commands ###
