"""add messages_json to api_requests

Revision ID: 2c783bee5481
Revises: 15ca813bb495
Create Date: 2026-03-04 17:30:27.733091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c783bee5481'
down_revision: Union[str, None] = '15ca813bb495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messages_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_requests', schema=None) as batch_op:
        batch_op.drop_column('messages_json')

    # ### end Alembic commands ###
