"""add complexity_score and complexity to api_requests

Revision ID: 3415480f748d
Revises: 2c783bee5481
Create Date: 2026-03-04 18:11:14.272723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3415480f748d'
down_revision: Union[str, None] = '2c783bee5481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complexity_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('complexity', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_requests', schema=None) as batch_op:
        batch_op.drop_column('complexity')
        batch_op.drop_column('complexity_score')

    # ### end Alembic commands ###
