"""add api_tool_uses table

Revision ID: e467833de78a
Revises: 3415480f748d
Create Date: 2026-03-04 18:49:39.708092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e467833de78a'
down_revision: Union[str, None] = '3415480f748d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tool_uses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('tool_use_id', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('input_preview', sa.String(length=500), nullable=True),
    sa.Column('result_preview', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['api_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_tool_uses', schema=None) as batch_op:
        batch_op.create_index('ix_api_tool_uses_request_id', ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_tool_uses', schema=None) as batch_op:
        batch_op.drop_index('ix_api_tool_uses_request_id')

    op.drop_table('api_tool_uses')
    # ### end Alembic commands ###
